# Basic dependabot.yml file with rust (cargo) configuration.

version: 2
updates:
  # Enable version updates for cargo (crates.io)
  - package-ecosystem: "cargo"
    # Look for `Cargo.toml` and `lock` files in the `root` directory
    directory: "/"
    # Check the registry for updates every day (weekdays)
    schedule:
      interval: "daily"
