# You'll need just to get started: `cargo install just`
# just manual: https://github.com/casey/just/#readme

_default:
    @just --list

{% if workspace %}
# Installs tools needed for other `just` recipes
install-tools:
    cargo install cargo-hack cargo-bump cargo-workspaces
{% else %}
# Installs tools needed for other `just` recipes
install-tools:
    cargo install cargo-hack cargo-bump
{% endif %}

# Checks (using `clippy`) all crates across all features
check:
    cargo hack --feature-powerset --exclude-no-default-features clippy --locked -- -D warnings

# Tests all crates across all features
test:
    cargo hack --feature-powerset --exclude-no-default-features test --locked

# Sets the version of the crate to `version`
set-version version:
    cargo bump {{version}}

{% if workspace %}
# Attempts to publish the crate using `cargo workspaces`
publish:
    cargo workspaces publish --from-git --no-git-commit --no-git-push --no-git-tag -y 
{% else %}
# Attempts to publish the crate using `cargo`
publish:
    cargo publish
{% endif %}