# This is a basic workflow to generate release artifacts for the full repo contents

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Use `release-please` to track changes and generate release PRs
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: simple
